import type { Metadata } from "next";
import { Inclusive_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inclusiveSans = Inclusive_Sans({
  variable: "--font-inclusive-sans",
  subsets: ["latin"],
});

const paperMono = localFont({
  src: "../public/fonts/PaperMono[wght].ttf",
  variable: "--font-paper-mono",
  weight: "100 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inclusiveSans.variable} ${paperMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="root">{children}</div>
      </body>
    </html>
  );
}
